### ISSUE TITLE
Why is circleci.yml using Context variables and not Environment variables?

### ISSUE THREAD

**Issue by rsoesemann** [sfdx-isv/sfdx-falcon-template#8]
It took me a while to find out that the template is NOT storing secrets in [Environment variables](https://circleci.com/docs/2.0/env-vars/) but in [Contexts](https://circleci.com/docs/2.0/contexts/). 

What's the difference and why did you decide to do so? From reading the docs it sounds like Environment variables on a specific project a more suitable.

**Comment by VivekMChawla** [comment]
Hi @rsoesemann - 

That's a fantastic question. Thanks for bringing it up.

CircleCI has the ability to store Environment Variables at a variety of levels.  You can declare them very "close to the metal" at the shell level in a run command in your config.yml file, or as far up as the project and organization scopes that you linked to in your question. 

Because "Contexts" enable you to set organization-wide environment variables that can be used across projects, they are very useful for certain kinds of secrets.  Dev Hub authentication secrets, in particular, work really well here because it's very likely that an ISV might have multiple projects that all require access to the same Dev Hub.

For example, an ISV with a base package and an extension package on the AppExchange should have two separate repositories for their code, one for each package.  They might even have a third repository for an unmanaged package that their services team uses to jump start client engagements.

The builds for each of those projects would need access to the same Dev Hub.  "Context" (ie. organizationally scoped) environment variables make that process a lot easier.

One thing that might be done differently is putting the packaging org secrets at the project level.  It's unlikely that you'd share those auth secrets between different projects.  It might be good for me to update the template to model that, although it will lead to an extra bit of complexity while setting up.

Does my explanation make sense?  Do you have any additional feedback?  These interactions are valuable because you're basically helping me draft what will go into the docs on this project once I can make time for a documentation sprint. 😄
